slogan: 一技之成，当尽毕生之力

menu:
  - title: 归档
    url: archives
    intro: All the articles.
    icon: fa fa-archive
  - title: 分类
    url: categories
    intro: All the categories.
    icon: fa fa-folder
  - title: 标签
    url: tags
    intro: All the tags.
    icon: fa fa-tags
  - title: 笔记
    url: mywiki
    intro: 无关风月的个人笔记
    icon: fa fa-tasks

  # - title: 关于
  #   url: about
  #   intro: About me.
  #   icon: fa fa-user

links:
  - title: Github
    url: http://www.github.com/huwenchao
    intro: My Github account.
    icon: fa fa-github
  - title: 微博
    url: http://t.sina.com.cn/zjuhwc
    intro: My sina weibo account.
    icon: fa fa-weibo
  - title: Freemind主题
    url: https://github.com/wzpan/freemind/
    intro: Freemind's Github repository.
    icon: fa fa-github
  - title: HaHack
    url: http://hahack.com/
    intro: Freemind主题作者的博客
    icon: fa fa-globe
  - title: 云风
    url: http://blog.codingnow.com/
    intro: 游戏程序员的偶像
    icon: fa fa-globe


widgets:
- search
- category
- tagcloud
- links

rss: atom.xml
favicon: img/logo.png
fancybox: true
duoshuo_shortname: huwenchao

# Analytics
google_analytics:
  enable: true
  siteid: UA-49755189-1
baidu_tongji:
  enable: false
  siteid:
#### Comment
# duoshuo:
#   enable: true  ## duoshuo.com
#   short_name: huwenchao    ## duoshuo short name.
#
# rss: atom.xml
# fancybox: true
# favicon: img/logo.png
# google_analytics: UA-49755189-1
